schema_version = 1
name = "vortex"
extension_config = "vane_extension_config.cmake"
build_extensions = ["httpfs", "parquet"]
native_test_selection = "test/*"

[vane]
repository = "AstroVela/vane"
revision = "5059e10e1f570ba6d93939d104e0f6e8152c56cb"
