schema_version = 2
name = "vortex"
extension_config = "extension_config_vane.cmake"
build_extensions = ["parquet"]
native_test_selection = "test/sql/sequence.test"

[vane]
repository = "AstroVela/vane"
revision = "4e12994a2fed5b872a7bdb44df72c1b9c5653cdc"

[vcpkg]
repository = "microsoft/vcpkg"
revision = "74e6536215718009aae747d86d84b78376bf9e09"
