[package]
name = "vortex-extension"
description = "C-compatible Vortex DuckDB extension artifacts"
edition = "2024"
publish = false

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
vortex-duckdb = { git = "https://github.com/AstroVela/vortex.git", rev = "3da8a2848b5d10d028e69471c5c97bd3dc785a03" }

# This improved build times significantly
[profile.dev.package.vortex-fastlanes]
debug = false

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
