[package]
name = "vortex-extension"
description = "C-compatible Vortex DuckDB extension artifacts"
edition = "2024"
publish = false

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
vortex-duckdb = { git = "https://github.com/AstroVela/vortex.git", rev = "6438f93778192b8bc3e887efcc17737dbcb79349" }
vortex-index-spfresh = { git = "https://github.com/AstroVela/vortex.git", rev = "6438f93778192b8bc3e887efcc17737dbcb79349", features = ["native"], optional = true }

[features]
index-spfresh = ["vortex-duckdb/index", "dep:vortex-index-spfresh"]

# This improved build times significantly
[profile.dev.package.vortex-fastlanes]
debug = false

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
