[package]
name = "vortex-extension"
description = "C-compatible Vortex DuckDB extension artifacts"
edition = "2024"
publish = false

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
vortex-duckdb = { git = "https://github.com/AstroVela/vortex.git", rev = "c6f7e497f99205937a6f4e73b4ab9ac3b74593b3" }
vortex-index-spfresh = { git = "https://github.com/AstroVela/vortex.git", rev = "c6f7e497f99205937a6f4e73b4ab9ac3b74593b3", features = ["native"], optional = true }

[features]
index-spfresh = ["vortex-duckdb/index", "dep:vortex-index-spfresh"]

# This improved build times significantly
[profile.dev.package.vortex-fastlanes]
debug = false

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
