[package]
name = "vortex-extension"
description = "C-compatible Vortex DuckDB extension artifacts for Vane"
edition = "2024"
publish = false

[workspace]
resolver = "2"

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
vortex-duckdb = { git = "https://github.com/AstroVela/vortex.git", rev = "1726615c7107e2b5e461c5a8767f682a4a02164f" }

[features]
vane = []

[profile.dev.package.vortex-fastlanes]
debug = false

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
