[package]
name = "vortex-extension"
description = "C-compatible Vortex DuckDB extension artifacts for Vane"
edition = "2024"
publish = false
build = "build.rs"

[workspace]
resolver = "2"

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
vortex-duckdb = { git = "https://github.com/AstroVela/vortex.git", rev = "090a557d0dc692dcd39b4b5823f2c06aa870fc83" }

[profile.dev.package.vortex-fastlanes]
debug = false

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
