[package]
name = "vortex-extension"
description = "C-compatible Vortex DuckDB extension artifacts for Vane"
license = "Apache-2.0"
edition = "2024"
publish = false
build = "build.rs"

[workspace]
resolver = "2"

[lib]
name = "vortex_duckdb"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[dependencies]
vortex-duckdb = { git = "https://github.com/AstroVela/vortex.git", rev = "114a1f2f59e6daf8377f1f2127b01652fd9448bf" }
vortex-index-spfresh = { git = "https://github.com/AstroVela/vortex.git", rev = "114a1f2f59e6daf8377f1f2127b01652fd9448bf", features = ["native"], optional = true }
vortex-index-hnswlib = { git = "https://github.com/AstroVela/vortex.git", rev = "114a1f2f59e6daf8377f1f2127b01652fd9448bf", features = ["native"], optional = true }

[features]
index-spfresh = ["vortex-duckdb/index", "dep:vortex-index-spfresh"]
index-hnswlib = ["vortex-duckdb/index", "dep:vortex-index-hnswlib"]

[profile.dev.package.vortex-fastlanes]
debug = false

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
